// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdiheghmbujxsaqpddpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkaWhlZ2htYnVqeHNhcXBkZHBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTg3MjIsImV4cCI6MjA2MDIzNDcyMn0.pgCJUXUK0zRqJ1KPvX24qQvQ3NySEI_Cc7QgMQExk3o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);